apiVersion: v1
kind: Secret
metadata:
  name:  mysql-secret
data:
   mysql_root_password: QmkzSTI3MDhqRVBIdw==
   mysql_username: ZmFsZWg=
   mysql_password: TFBnd2Y1TlB3Z2NLZw==
   mysql_dbname: ZmFsZWg=
type: Opaque
