apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  labels:
    storage-tier: nfs
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfs
    server: 95.179.254.196
