version: "3.9"

services:
  db:
    image: mysql
    restart: always
    container_name: mysql
    expose:
      - 3306
    volumes:
      - db-data:/var/lib/mysql
    secrets:
      - db-creds
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-creds
      MYSQL_USER_FILE: /run/secrets/db-creds
      MYSQL_PASSWORD_FILE: /run/secrets/db-creds
      MYSQL_DATABASE_FILE: /run/secrets/db-creds
    networks:
      - db
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10


  app:
    image: elfaleh/python-app
    restart: always
    container_name: python-app
    expose:
      - 5000
    env_file:
      - mysql-creds.env
    environment:
      VIRTUAL_HOST: app.test.fixed
      VIRTUAL_PORT: 5000
    networks:
      - db
      - web
    healthcheck:
      test: ["CMD", "curl" ,"--fail", "-s", "http://localhost:5000/"]
      timeout: 20s
      retries: 10
    depends_on:
      db:
        condition: service_healthy

  pma:
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      VIRTUAL_HOST: phpmyadmin.test.fixed
    networks:
      - db
      - web
    healthcheck:
      test: ["CMD", "curl" ,"--fail", "-s", "http://localhost:80/"]
      timeout: 20s
      retries: 10
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data: 
    driver: local
secrets:
  db-creds:
    file: ./mysql-creds
networks:
  web:
  db:

